### ISSUE TITLE
Make alternate script that builds the same, but in a jail

### ISSUE THREAD

**Issue by theGeeBee** [theGeeBee/NextCloudOnFreeBSD#1]
* iocage
* create dataset in host and set mounts accordingly
* use iocage commands to perform the rest of the scripted tasks
* somehow make sure that the scripts share as much as possible

**Comment by jdakhayman** [comment]
Or possibly consider using BastilleBSD? Maybe?

jda

**Comment by lispstudent** [comment]
Some use Dan Langille's simpler [mkjail](https://github.com/mkjail/mkjail).  Some, [CBSD](https://eerielinux.wordpress.com/2022/12/10/exploring-the-cbsd-virtual-environment-management-framework-part-1-introduction-and-installation/).
