### ISSUE TITLE
HSTS is stopping Nextcloud from loading after running install.sh

### ISSUE THREAD

**Issue by jahway603** [theGeeBee/NextCloudOnFreeBSD#13]
OS used: FreeBSD 14.x

HSTS is stopping Nextcloud from loading after running `install.sh`. I have followed the README instructions and after `install.sh` finishes, I navigate to the web URL in my browser & get the following:

```
Your connection is not private
Attackers might be trying to steal your information from nextcloud.MY-WEBSITE.com (for example, passwords, messages, or credit cards). [Learn more](chrome-error://chromewebdata/#)
NET::ERR_CERT_AUTHORITY_INVALID
nextcloud.MY-WEBSITE.com normally uses encryption to protect your information. When Chromium tried to connect to nextcloud.MY-WEBSITE.com this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be nextcloud.MY-WEBSITE.com, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Chromium stopped the connection before any data was exchanged.

You cannot visit nextcloud.MY-WEBSITE.com right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later.
```
- I changed my actual website name in the error for privacy purposes

Any ideas on how to disable HSTS? Or anything else I need to do to get this working?

**Comment by jahway603** [comment]
The default is set a "self-signing" cert, which does not work with HSTS.

I eventually figured out which certain apache config options to edit and then manually used certbot to get a valid cert - and now I can get to the nextcloud thru the web browser.

Idea: edit `install.sh` to not use/setup HSTS if a self-signed cert is setup.

**Comment by johndo100** [comment]
You can look in the source where nginx handle SSL.
I made a change to make it work behind reverse proxy in jail before.
You can try it in a jail, it should works.
Other way you can do is set your SSL manually: get it from letenscript for example..

**Comment by theGeeBee** [comment]
Please share details of your setup?

Browser, etc. I've not experienced that with my default test environment.

I have also made a change to allow you to generate LetsEncrypt certificate by setting SSL cert option to "public".

I will have a look in the coming days

**Comment by theGeeBee** [comment]
> OS used: FreeBSD 14.x
> 
> HSTS is stopping Nextcloud from loading after running `install.sh`. I have followed the README instructions and after `install.sh` finishes, I navigate to the web URL in my browser & get the following:
> 
> ```
> Your connection is not private
> Attackers might be trying to steal your information from nextcloud.MY-WEBSITE.com (for example, passwords, messages, or credit cards). [Learn more](chrome-error://chromewebdata/#)
> NET::ERR_CERT_AUTHORITY_INVALID
> nextcloud.MY-WEBSITE.com normally uses encryption to protect your information. When Chromium tried to connect to nextcloud.MY-WEBSITE.com this time, the website sent back unusual and incorrect credentials. This may happen when an attacker is trying to pretend to be nextcloud.MY-WEBSITE.com, or a Wi-Fi sign-in screen has interrupted the connection. Your information is still secure because Chromium stopped the connection before any data was exchanged.
> 
> You cannot visit nextcloud.MY-WEBSITE.com right now because the website uses HSTS. Network errors and attacks are usually temporary, so this page will probably work later.
> ```
> 
>     * I changed my actual website name in the error for privacy purposes
> 
> 
> Any ideas on how to disable HSTS? Or anything else I need to do to get this working?

Hi,

I have updated the script to disable HSTS if SSL is disabled moving forward.

For now though, you can edit /usr/local/etc/apache24/vhosts/your_hostname.conf

Comment out these lines:

```
<IfModule mod_headers.c>

      Header always set Strict-Transport-Security "max-age=15552000; includeSubDomains"

</IfModule>
```
    
Then you can restart apache by running:
```sudo apachectl graceful```
