### ISSUE TITLE
[Feature Request] Create option to use nginx instead of Apache

### ISSUE THREAD

**Issue by jahway603** [theGeeBee/NextCloudOnFreeBSD#14]
I initially forked your repo to change Apache to nginx, as I work with nginx on my other Nextcloud servers, but I'm new to *BSD so will first need to learn more about nginx's setup on FreeBSD to be able to do that. I've opened this to track my progress on this Feature Request.

**Comment by theGeeBee** [comment]
Hi,

We can definitely do that. I was focused on only running on what is "recommened" by the nextcloud documentation, hence Apache/MariaDB, etc. 

I will work on this.
