### ISSUE TITLE
Separate Onlyoffice Document Server as VM

### ISSUE THREAD

**Issue by theGeeBee** [theGeeBee/NextCloudOnFreeBSD#3]
Have the option to install an Ubuntu(?) server as VM to run a "proper" document server on the same machine using Bhyve.
This will give better performance and reliability for more robust deployment suitable for business.

**Comment by MikaelUrankar** [comment]
FYI we have native onlyoffice-documentserver on FreeBSD for quite some time www/onlyoffice-documentserver

**Comment by theGeeBee** [comment]
> FYI we have native onlyoffice-documentserver on FreeBSD for quite some time www/onlyoffice-documentserver

Hi! Yes! I found it and started testing after adding this issue. Working on integrating it. 

Thanks for the port! 🙂

**Comment by Pashugan** [comment]
I didn't manage to make OnlyOffice working, though they have had a few releases after I last tried. If someone like me is just looking for pages like Confluence, [Collectives](https://apps.nextcloud.com/apps/collectives) is exactly that (in disguise).
