### ISSUE TITLE
Automatic TLS provisioning supplied by Apache itself

### ISSUE THREAD

**Issue by lispstudent** [theGeeBee/NextCloudOnFreeBSD#5]
Thank you for [NextCloudOnFreeBSD](https://github.com/theGeeBee/NextCloudOnFreeBSD), I came here via a [/r/freebsd/](https://old.reddit.com/r/freebsd/comments/vec8au/nextcloudonfreebsd_automate_installation_of/).

I tried it and have it working smoothly,  exactly what I needed.

You probably already know this, but Apache 2.4 handles automatic TLS provisioning, via the [Apache md](https://httpd.apache.org/docs/2.4/mod/mod_md.html) module.

In `httpd.conf`:

- Uncomment the line starting with `LoadModule md_module`

- At the end, before last line: `Include etc/apache24/Includes/*.conf` add

```
<Ifmodule md_module>
MDCertificateAgreement accepted
</IfModule>
```

In a site.conf, just add this at the bottom of `VirtualHost`, substituting anything one may have about other certificates. 

```
<VirtualHost *:443>
  [...]
    SSLEngine on
    # no certificates specification needed
</VirtualHost>
```

Would you consider enabling such automatic provisioning by default?

**Comment by lispstudent** [comment]
PS: I have found I need to reload Apache twice: once to have it read the edited site.conf, the second time to have the certificate delivered and installed.

On my server, something like this suffice:

```
apachectl graceful ; sleep 1 ; apachectl graceful

```

**Comment by theGeeBee** [comment]
I did not know that - will check it out. Thanks!

I do want to have a "make it public" kind of extra step as an option. At the moment it's for LAN only.
