### ISSUE TITLE
Possibly update script to Php82 and MariaDB?

### ISSUE THREAD

**Issue by lispstudent** [theGeeBee/NextCloudOnFreeBSD#8]
Hello,

Thank you for [NextCloudOnFreeBSD](https://github.com/theGeeBee/NextCloudOnFreeBSD).

I used it with success while other options were not working, it is the easiest and more customisable way to install NextCloud on FreeBSD.

Starting from version 26.0.2, NextCloud supports Php 8.2 and MariaDB 10.6 as [recommended versions](https://docs.nextcloud.com/server/latest/admin_manual/installation/system_requirements.html).

Since Ports will be quite behind in this (supporting Php82), would you consider upgrading the Requirements.txt file?

MariaDB seems to be the server more used in NC documentation, would you also consider using [MariaDB 10.6](https://www.freshports.org/databases/mariadb106-server/) instead of [MySQL](https://github.com/theGeeBee/NextCloudOnFreeBSD/blob/7a4fdb36e3ba5cf350474b735e4006b1785b421d/includes/requirements.txt#LL11C1-L11C15)?

Thank you for consider it.

**Comment by theGeeBee** [comment]
I am publishing a new version in the next day.

It will install NC27 / php8.2 / mariaDB10.6
